[project]
name = "kernelwealthfunds"
version = "1.0.0"
description = "A repository to keep track of the components of Kernel Wealth funds"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.0",
    "requests>=2.32.4",
    "scipy>=1.16.1",
    "seaborn>=0.13.2",
]
